ite_name: GPT Docs

nav:
    - Главная: index.md
    - Структура проекта: project_structure.md
    - Деплой: deploy_guide.md
    - API: api_reference.md
    - Заметки: notes.md

theme:
    name: "material"
    language: ru
    palette:
        - scheme: slate
          primary: red
          accent: lime
          toggle:
            icon: material/lightbulb
            name: Включить светлую тему 

        - scheme: default
          primary: red
          accent: lime
          toggle:
            icon: material/lightbulb-outline
            name: Включить тёмную тему
    features:
        - content.code.copy
        - navigation.tracking
        - navigation.footer
        - navigation.path
        - navigation.prune
        - toc.follow
        - toc.integrate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji 
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
        custom_checkbox: true
  - attr_list
  - tables
        
plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        selection:
          docstring_style: google
- autorefs
- privacy
- offline

extra:
  social:
    - icon: fontawesome/brands/git-alt
      link: http://locahost
